insert into houses (houseNumber, streetName, postcode, city, ownerId) values (167, 'Burning Wood', 1550, 'Molchanovo', 24);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (197, 'Garrison', 1892, 'Šilheřovice', 2);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (138, 'Larry', 1942, 'Zhongxiao', 3);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (28, 'Twin Pines', 1833, 'Komyshnya', 12);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (84, 'Havey', 1795, 'Chuangye', 35);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (121, 'Clyde Gallagher', 1876, 'Vykhino-Zhulebino', 1);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (190, 'Norway Maple', 1573, 'Mtinko', 7);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (123, 'Larry', 1873, 'La Broquerie', 7);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (119, 'Ruskin', 1032, 'Bolekhiv', 46);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (21, 'Cottonwood', 1841, 'Umm as Sāhik', 23);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (106, 'Jana', 1327, 'Yuetang', 12);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (78, 'Dahle', 1147, 'Paranapanema', 10);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (50, 'Canary', 1989, 'Zaporizhzhya', 36);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (173, 'Namekagon', 1125, 'Tangchi', 45);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (90, 'Esch', 1116, 'Kolomak', 9);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (157, 'Park Meadow', 1036, 'Haiyang', 28);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (99, 'Blue Bill Park', 1633, 'Wentai', 21);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (34, 'Jenifer', 1674, 'Gränna', 17);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (160, 'Walton', 1245, 'Jingang', 8);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (98, '3rd', 1947, 'Baykonyr', 19);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (215, 'Petterle', 1710, 'Gaphatshwe', 42);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (190, '4th', 1884, 'Futuroscope', 22);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (214, 'Service', 1347, 'Nanga Eboko', 44);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (168, 'Spaight', 1473, 'Shibukawa', 6);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (26, 'Paget', 1930, 'Tasovčići', 30);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (100, 'Kim', 1317, 'Shuinan', 41);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (178, 'Northridge', 1327, 'Dallas', 41);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (183, 'Surrey', 1169, 'Jurangjero', 9);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (37, 'Crowley', 1992, 'Pakuwon', 2);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (169, 'Buena Vista', 1780, 'Mtsamdou', 13);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (41, 'Dwight', 1123, 'Libertador General San Martín', 35);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (154, 'Monica', 1644, 'Sukamaju Kidul', 14);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (20, 'Kim', 1198, 'Matangpayang', 1);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (62, 'New Castle', 1795, 'Patos de Minas', 22);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (126, 'Del Sol', 1002, 'Paris 12', 14);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (159, 'Farragut', 1355, 'Catamayo', 37);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (104, 'Ronald Regan', 1026, 'Bandungsari', 40);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (133, 'Florence', 1321, 'Omoku', 48);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (100, 'Pennsylvania', 1036, 'Zengguang', 50);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (144, 'Brickson Park', 1681, 'Doba', 28);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (75, 'Judy', 1409, 'Pinhal Novo', 19);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (177, 'Hazelcrest', 1454, 'Puntarenas', 28);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (35, 'Tennyson', 1786, 'Lüxiang', 28);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (64, 'Daystar', 1738, 'Mempawah', 20);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (99, 'Vernon', 1823, 'Sembung', 37);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (209, 'Corscot', 1767, 'Dukoh', 37);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (80, 'Messerschmidt', 1266, 'Buenavista', 14);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (111, 'Morningstar', 1442, 'Ebene', 13);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (110, 'Fisk', 1006, 'Jiushe', 10);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (195, 'Trailsway', 1404, 'Az Zaytūnīyah', 12);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (56, 'Swallow', 1460, 'Issoudun', 26);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (97, 'Dixon', 1987, 'San Cristóbal Cucho', 4);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (174, '5th', 1538, 'Drayton Valley', 3);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (184, 'Milwaukee', 1428, 'Xingxi', 23);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (111, 'Lawn', 1394, 'Yabuli', 41);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (145, '2nd', 1463, 'Nerk’in Getashen', 1);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (111, 'Spaight', 1580, 'Shuanggang', 43);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (10, 'Fremont', 1062, 'Ogaminan', 13);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (174, 'Starling', 1287, 'Linshui', 46);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (167, 'Milwaukee', 1400, 'Haikou', 17);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (100, 'Reinke', 1056, 'Guiniculalay', 34);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (152, 'Nancy', 1678, 'Pyinmana', 23);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (23, 'Division', 1018, 'Karang Daye', 17);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (63, 'Hoffman', 1599, 'Kimberley', 32);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (184, 'Lunder', 1065, 'Daba', 21);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (167, 'Tony', 1264, 'Rognedino', 33);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (211, 'Jenifer', 1599, 'Stryszów', 7);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (26, 'Grayhawk', 1988, 'Baizhang', 25);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (159, 'Brown', 1702, 'Một Ngàn', 2);
insert into houses (houseNumber, streetName, postcode, city, ownerId) values (214, 'Rigney', 1749, 'Santa Rosa', 11);

insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Maribel', 'Adel', 35, 2, 37);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Olivie', 'Caulfield', 51, 2, 33);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Bastian', 'Youings', 50, 3, 20);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Thorstein', 'Eadington', 41, 2, 19);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Redford', 'Spear', 6, 2, 41);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Petrina', 'Cassin', 2, 4, 27);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Esteban', 'Sherington', 23, 2, 3);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Sibbie', 'Lammenga', 14, 2, 60);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Bernhard', 'Reams', 18, 5, 97);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Fremont', 'Beckers', 31, 4, 17);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Jae', 'Dongate', 48, 4, 29);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Crissie', 'De la Feld', 59, 3, 54);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Cindelyn', 'Conre', 11, 5, 56);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Wolfgang', 'Grevel', 26, 1, 48);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Solly', 'Irving', 10, 3, 46);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Oralle', 'Eldered', 43, 5, 15);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Minny', 'Safhill', 50, 2, 92);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Shelby', 'Isson', 22, 5, 52);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Ozzie', 'Newing', 67, 1, 34);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Sabina', 'Knight', 45, 4, 13);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Thadeus', 'Bonnette', 1, 3, 15);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Maggy', 'Drinnan', 70, 5, 12);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Bettye', 'Machin', 46, 4, 34);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Georgine', 'Gambles', 31, 1, 16);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Mair', 'Sporton', 66, 6, 57);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Lida', 'Carlick', 41, 3, 86);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Blaire', 'Stonier', 62, 3, 31);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Zechariah', 'Nibloe', 66, 4, 7);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Addy', 'Bollands', 6, 4, 23);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Janis', 'Keepence', 18, 2, 63);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Claire', 'Hartshorne', 26, 5, 90);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Gwyneth', 'Neaves', 29, 2, 14);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Giselbert', 'Claiton', 51, 4, 26);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Jeane', 'Pallant', 20, 6, 93);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Mark', 'Degg', 65, 3, 37);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Conrado', 'Overill', 26, 2, 22);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Duffie', 'Kilfeder', 27, 4, 36);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Natalina', 'Legendre', 21, 3, 34);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Pedro', 'Sneden', 10, 5, 40);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Val', 'Entwhistle', 65, 1, 51);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Claudius', 'Meneely', 53, 3, 6);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Fonz', 'Rizziello', 51, 6, 48);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Fayre', 'McElwee', 9, 6, 78);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Con', 'Harwood', 13, 3, 21);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Emlynne', 'Johnstone', 65, 4, 80);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Brittni', 'Beever', 62, 1, 5);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Franklin', 'Craydon', 37, 2, 18);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Steven', 'Landeg', 48, 4, 57);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Erwin', 'Kesten', 37, 1, 46);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Dav', 'Gauvin', 3, 2, 66);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Leonerd', 'Kinzett', 36, 1, 84);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Meris', 'Nobes', 5, 5, 74);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Tiebout', 'Cargenven', 57, 1, 90);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Dreddy', 'McElvogue', 29, 1, 84);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Lind', 'Portlock', 17, 3, 39);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Welbie', 'Arnholz', 33, 2, 69);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Kamillah', 'Haruard', 50, 6, 12);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Elyn', 'Bolton', 54, 4, 51);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Ara', 'Gierek', 70, 3, 18);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Nickola', 'Faherty', 28, 3, 88);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Maia', 'Iwanicki', 40, 5, 68);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Randie', 'Peasgood', 66, 2, 18);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Elsey', 'Hemphill', 47, 4, 26);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Tandi', 'Gallahue', 39, 3, 93);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Aundrea', 'Openshaw', 33, 2, 28);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Robinett', 'Jackson', 51, 4, 15);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Desiri', 'Rubinowitsch', 16, 6, 15);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Dorri', 'Adnett', 65, 4, 96);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Rhodie', 'Onge', 63, 4, 99);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Donaugh', 'Mowsdill', 29, 5, 38);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Warren', 'Dunnett', 26, 6, 84);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Dory', 'Steeples', 21, 1, 39);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Johnath', 'Newman', 41, 2, 28);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Rhodia', 'Bullent', 50, 2, 53);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Jaquith', 'Ewer', 12, 3, 53);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Prudy', 'Caville', 49, 3, 11);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Peter', 'Karolowski', 51, 2, 19);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Shem', 'Merrick', 68, 6, 59);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Cletus', 'Hathwood', 26, 5, 89);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Felicity', 'Pettipher', 44, 4, 59);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Janot', 'Barber', 14, 5, 28);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Ellary', 'Picker', 2, 6, 89);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Pietra', 'Blasius', 7, 2, 55);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Bethany', 'De Fries', 22, 4, 81);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Shannon', 'Tilbey', 2, 1, 57);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Celine', 'Mongan', 45, 2, 19);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Winslow', 'Sides', 2, 4, 73);
insert into owners (firstName, lastName, houseId, noOfOccupants, age) values ('Ginni', 'Sexty', 51, 6, 74);

